language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
script: "rspec spec"

# Install libsodium.
before_install:
  - wget http://download.libsodium.org/libsodium/releases/LATEST.tar.gz -O libsodium.tar.gz
  - tar xf libsodium.tar.gz
  - "cd libsodium* && ./configure --prefix $TRAVIS_BUILD_DIR/sodium && cd ../"
  - make -C ./libsodium*
  - make -C ./libsodium* install

env: "LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/sodium/lib"