language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
script: "rspec spec"

# Install libsodium.
before_install:
  - wget http://download.libsodium.org/libsodium/releases/libsodium-0.4.tar.gz -O libsodium.tar.gz
  - tar xf libsodium.tar.gz
  - "cd libsodium-0.4 && ./configure --prefix $PWD/lib && cd ../"
  - make -C ./libsodium-0.4
  - make -C ./libsodium-0.4 install

env: "LD_LIBRARY_PATH=$PWD/libsodium-0.4/out/lib"
